name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://my-cloud-resume-challenge-aws --exclude ".*" --exclude "github/*"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key  }}
